---
  parser: "babel-eslint"

  ecmaFeatures:
    arrowFunctions: true
    blockBindings: true
    classes: true
    defaultParams: true
    destructuring: true
    forOf: true
    generators: true
    modules: true
    objectLiteralComputedProperties: true
    objectLiteralShorthandMethods: true
    objectLiteralShorthandProperties: true
    restParams: true
    spread: true
    templateStrings: true
    jsx: true

  extends: "airbnb"

  globals:
    log: false

  rules:
    comma-dangle:
      - 1
      - "always-multiline"

    new-cap:
      - 2
      - capIsNewExceptions:
        - "Collection"
        - "Iterable"
        - "List"
        - "Map"
        - "OrderedMap"
        - "OrderedSet"
        - "Range"
        - "Record"
        - "Repeat"
        - "Seq"
        - "Set"
        - "Stack"

    object-curly-spacing:
      - 1
      - "never"
